spring.datasource.url=jdbc:mysql://127.0.0.1:3306/shoetec?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect